spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongo_admin
      password: mongo_password
      database: mongo_poc
      port: 27017
      host: localhost
      auto-index-creation: true